services:
  api:
    build: .
    container_name: backend-api
    ports:
      - '3000:3000'
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mysql
    environment:
      DATABASE_URL: 'mysql://root:root@mysql:3306/app_database'
      DATABASE_USER: 'root'
      DATABASE_PASSWORD: 'root'
      DATABASE_NAME: 'app_database'
      DATABASE_HOST: 'mysql'
      DATABASE_PORT: 3306

  mysql:
    image: mysql:8
    container_name: mysql-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
